-- MicroShort Database Schema Reference
-- This file is a COPY of the Supabase migration for documentation.
-- The source of truth is supabase/migrations/
-- Do NOT edit this file directly. Edit the migration and copy here.

-- MicroShort Content Hierarchy Schema
-- Migration: 00000000000001_create_content_schema
-- Creates: Series > Seasons > Episodes content hierarchy with profiles
-- Business rules enforced at database level via CHECK constraints and triggers

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Genres enum for consistent categorization
CREATE TYPE genre AS ENUM (
  'drama', 'comedy', 'thriller', 'sci-fi', 'horror',
  'romance', 'action', 'documentary', 'behind-the-scenes',
  'music', 'sports'
);

-- Content status workflow
CREATE TYPE content_status AS ENUM (
  'draft', 'processing', 'ready', 'published', 'archived'
);

-- ============================================================================
-- TABLES
-- ============================================================================

-- Series: top-level content entity
CREATE TABLE public.series (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  genre genre NOT NULL,
  thumbnail_url TEXT,
  trailer_url TEXT,
  creator_id UUID NOT NULL,  -- FK added after profiles table exists
  status content_status NOT NULL DEFAULT 'draft',
  is_featured BOOLEAN NOT NULL DEFAULT false,
  view_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seasons: ordered groupings within a series
CREATE TABLE public.seasons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  series_id UUID NOT NULL REFERENCES public.series(id) ON DELETE CASCADE,
  season_number INTEGER NOT NULL,
  title TEXT,
  description TEXT,
  price_cents INTEGER,  -- creator-set price (NULL = free)
  status content_status NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Enforce unique season numbers within a series
  UNIQUE (series_id, season_number),

  -- Price must be positive if set
  CHECK (price_cents IS NULL OR price_cents > 0)
);

-- Episodes: individual video content
CREATE TABLE public.episodes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  season_id UUID NOT NULL REFERENCES public.seasons(id) ON DELETE CASCADE,
  episode_number INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  duration_seconds INTEGER,  -- set by Mux webhook when asset is ready
  mux_asset_id TEXT,
  mux_playback_id TEXT,
  thumbnail_url TEXT,
  subtitle_url TEXT,          -- WebVTT file URL
  status content_status NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Enforce unique episode numbers within a season
  UNIQUE (season_id, episode_number),

  -- Episodes must be 1-3 minutes (60-180 seconds) when duration is known
  CHECK (duration_seconds IS NULL OR (duration_seconds >= 60 AND duration_seconds <= 180))
);

-- Profiles: user accounts (extends Supabase Auth)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  display_name TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('viewer', 'creator', 'admin')),
  bio TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- FOREIGN KEYS (added after dependent tables exist)
-- ============================================================================

-- Add foreign key for series.creator_id now that profiles exists
ALTER TABLE public.series
  ADD CONSTRAINT fk_series_creator
  FOREIGN KEY (creator_id) REFERENCES public.profiles(id);

-- ============================================================================
-- TRIGGER FUNCTIONS
-- ============================================================================

-- Season episode count enforcement via trigger
-- (8-70 episodes per season -- enforced on publish, not on insert)
CREATE OR REPLACE FUNCTION check_season_episode_count()
RETURNS TRIGGER AS $$
DECLARE
  episode_count INTEGER;
BEGIN
  IF NEW.status = 'published' THEN
    SELECT COUNT(*) INTO episode_count
    FROM public.episodes
    WHERE season_id = NEW.id AND status = 'published';

    IF episode_count < 8 OR episode_count > 70 THEN
      RAISE EXCEPTION 'Published seasons must have 8-70 published episodes (found %)', episode_count;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER enforce_season_episode_count
  BEFORE UPDATE ON public.seasons
  FOR EACH ROW
  WHEN (NEW.status = 'published')
  EXECUTE FUNCTION check_season_episode_count();

-- Updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to all content tables
CREATE TRIGGER series_updated_at BEFORE UPDATE ON public.series
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER seasons_updated_at BEFORE UPDATE ON public.seasons
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER episodes_updated_at BEFORE UPDATE ON public.episodes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

-- Enable RLS on all content tables
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Public read access for published content
CREATE POLICY "Published series are visible to everyone"
  ON public.series FOR SELECT
  USING (status = 'published');

CREATE POLICY "Published seasons are visible to everyone"
  ON public.seasons FOR SELECT
  USING (status = 'published');

CREATE POLICY "Published episodes are visible to everyone"
  ON public.episodes FOR SELECT
  USING (status = 'published');

CREATE POLICY "Profiles are visible to everyone"
  ON public.profiles FOR SELECT
  USING (true);

-- Creators can manage their own series
CREATE POLICY "Creators can manage own series"
  ON public.series FOR ALL
  USING ((SELECT auth.uid()) = creator_id);

-- Creators can manage seasons/episodes in their series
CREATE POLICY "Creators can manage own seasons"
  ON public.seasons FOR ALL
  USING (
    series_id IN (
      SELECT id FROM public.series WHERE creator_id = (SELECT auth.uid())
    )
  );

CREATE POLICY "Creators can manage own episodes"
  ON public.episodes FOR ALL
  USING (
    season_id IN (
      SELECT s.id FROM public.seasons s
      JOIN public.series sr ON s.series_id = sr.id
      WHERE sr.creator_id = (SELECT auth.uid())
    )
  );

-- Users can manage their own profile
CREATE POLICY "Users can manage own profile"
  ON public.profiles FOR ALL
  USING ((SELECT auth.uid()) = id);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX idx_series_genre ON public.series(genre) WHERE status = 'published';
CREATE INDEX idx_series_creator ON public.series(creator_id);
CREATE INDEX idx_series_featured ON public.series(is_featured) WHERE status = 'published';
CREATE INDEX idx_seasons_series ON public.seasons(series_id);
CREATE INDEX idx_episodes_season ON public.episodes(season_id);
CREATE INDEX idx_profiles_role ON public.profiles(role);

-- ============================================================================
-- PURCHASES & PRICING (Migration 00000000000003)
-- ============================================================================

-- Price tiers: preset pricing options for seasons
CREATE TABLE public.price_tiers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  label TEXT NOT NULL,
  price_cents INTEGER NOT NULL CHECK (price_cents > 0),
  stripe_price_id TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.price_tiers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Active price tiers are visible to everyone"
  ON public.price_tiers FOR SELECT
  USING (is_active = true);

-- Seed initial price tiers
INSERT INTO public.price_tiers (label, price_cents, sort_order) VALUES
  ('Budget',      299, 1),
  ('Standard',    499, 2),
  ('Premium',     799, 3),
  ('Deluxe',      999, 4),
  ('Blockbuster', 1499, 5);

-- Seasons: link to price tiers
ALTER TABLE public.seasons
  ADD COLUMN price_tier_id UUID REFERENCES public.price_tiers(id);

-- Profiles: Stripe Connect fields
ALTER TABLE public.profiles
  ADD COLUMN stripe_account_id TEXT,
  ADD COLUMN stripe_onboarding_complete BOOLEAN NOT NULL DEFAULT false;

-- Series: bundle discount percentage
ALTER TABLE public.series
  ADD COLUMN bundle_discount_percent INTEGER DEFAULT 15
    CHECK (bundle_discount_percent IS NULL OR (bundle_discount_percent >= 0 AND bundle_discount_percent <= 50));

-- Purchases: records of completed season unlocks
CREATE TABLE public.purchases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id),
  season_id UUID NOT NULL REFERENCES public.seasons(id),
  creator_id UUID NOT NULL REFERENCES public.profiles(id),
  stripe_session_id TEXT UNIQUE NOT NULL,
  stripe_payment_intent_id TEXT,
  stripe_charge_id TEXT,
  amount_cents INTEGER NOT NULL,
  platform_fee_cents INTEGER NOT NULL,
  creator_share_cents INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'completed'
    CHECK (status IN ('completed', 'refunded')),
  transferred BOOLEAN NOT NULL DEFAULT false,
  stripe_transfer_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (user_id, season_id)
);

ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own purchases"
  ON public.purchases FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Creators can view purchases of their content"
  ON public.purchases FOR SELECT
  USING ((SELECT auth.uid()) = creator_id);

CREATE INDEX idx_purchases_user ON public.purchases(user_id);
CREATE INDEX idx_purchases_season ON public.purchases(season_id);
CREATE INDEX idx_purchases_creator ON public.purchases(creator_id);
CREATE INDEX idx_purchases_untransferred ON public.purchases(creator_id)
  WHERE transferred = false;

-- Payout records: tracks completed transfers to creator Connect accounts
CREATE TABLE public.payout_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  creator_id UUID NOT NULL REFERENCES public.profiles(id),
  purchase_id UUID NOT NULL REFERENCES public.purchases(id),
  stripe_transfer_id TEXT NOT NULL,
  amount_cents INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'completed'
    CHECK (status IN ('completed', 'failed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.payout_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Creators can view own payouts"
  ON public.payout_records FOR SELECT
  USING ((SELECT auth.uid()) = creator_id);

CREATE INDEX idx_payouts_creator ON public.payout_records(creator_id);
